services:
  database:
    image: postgres:17.5-alpine3.22
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=zeste
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
volumes:
  psql-data:
